### PR TITLE
Prevent LockedStream console error by providing metaData in advance

### LINKED ISSUE #46: Console error in the Editor and FE when previewing the Winamp Player
### Describe the bug

Once I add the Winamp Block in the editor and try to preview the Winamp Player in the editor I get a few console errors.

### Steps to Reproduce

- Add the Winamp Block to the page/post in the editor.
- Add audio to the Winamp Block
- Click on Preview Player option in the block toolbar
- You can now see the console error in your browser console window.

### Screenshots, screen recording, code snippet

**Screen Recording:**
https://share.getcloudapp.com/lluE8rB1

**Editor:** 
Screenshot 2022-04-20 at 4 08 54 PM

**Front End:**
Screenshot 2022-04-20 at 4 09 20 PM

### Environment information

Macbook: 12.3.1
Google Chrome: Version 100.0.4896.127 (Official Build) (x86_64)

### WordPress information

`
### wp-core ###

version: 5.9.3
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/html
wordpress_size: loading...
uploads_path: /var/www/html/wp-content/uploads
uploads_size: loading...
themes_path: /var/www/html/wp-content/themes
themes_size: loading...
plugins_path: /var/www/html/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (1) ###

db.php: true

### wp-active-theme ###

name: Twenty Twenty-One (twentytwentyone)
version: 1.4 (latest version: 1.5)
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, automatic-feed-links, title-tag, post-formats, post-thumbnails, menus, html5, custom-logo, customize-selective-refresh-widgets, wp-block-styles, align-wide, editor-styles, editor-style, editor-font-sizes, custom-background, editor-color-palette, editor-gradient-presets, responsive-embeds, custom-line-height, experimental-link-color, custom-spacing, custom-units, widgets
theme_path: /var/www/html/wp-content/themes/twentytwentyone
auto_update: Disabled

### wp-themes-inactive (10) ###

10up Theme: version: 0.1.0, author: 10up, Auto-updates disabled
Astra: version: 3.7.3, author: Brainstorm Force (latest version: 3.7.10), Auto-updates disabled
Newspack Joseph: version: 1.50.0, author: Automattic, Auto-updates disabled
Newspack Katharine: version: 1.50.0, author: Automattic, Auto-updates disabled
Newspack Nelson: version: 1.50.0, author: Automattic, Auto-updates disabled
Newspack Sacha: version: 1.50.0, author: Automattic, Auto-updates disabled
Newspack Scott: version: 1.50.0, author: Automattic, Auto-updates disabled
Newspack: version: 1.50.0, author: Automattic, Auto-updates disabled
Twenty Twenty: version: 1.8, author: the WordPress team (latest version: 1.9), Auto-updates disabled
Twenty Twenty-Two: version: 1.1, author: the WordPress team, Auto-updates disabled

### wp-mu-plugins (1) ###

10up Plugin Scaffold: version: 0.1.0, author: 10up

### wp-plugins-active (6) ###

Ad Refresh Control: version: 1.0.5, author: 10up, Auto-updates disabled
ClassifAI: version: 1.7.0, author: 10up, Auto-updates disabled
Debug Bar: version: 1.1.2, author: wordpressdotorg, Auto-updates disabled
Insert Special Characters: version: 1.0.3, author: 10up (latest version: 1.0.4), Auto-updates disabled
Query Monitor: version: 3.8.1, author: John Blackbourn (latest version: 3.9.0), Auto-updates disabled
Retro Winamp Block: version: 1.0.1, author: 10up, Auto-updates disabled

### wp-plugins-inactive (6) ###

Akismet Anti-Spam: version: 4.1.12, author: Automattic (latest version: 4.2.2), Auto-updates disabled
Block for Apple Maps: version: 1.0.1, author: 10up (latest version: 1.0.2), Auto-updates disabled
Hello Dolly: version: 1.7.2, author: Matt Mullenweg, Auto-updates disabled
Insecure Content Warning: version: 1.0.0, author: 10up (latest version: 1.0.1), Auto-updates disabled
Publisher Media Kit: version: 1.0.0, author: 10up (latest version: 1.1.0), Auto-updates disabled
Simple Podcasting: version: 1.2.0, author: 10up (latest version: 1.2.2), Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1692
imagemagick_version: ImageMagick 6.9.12-19 Q16 x86_64 2021-07-18 https://imagemagick.org
imagick_version: 3.5.1
file_uploads: File uploads is turned off
post_max_size: 150m
upload_max_filesize: 150m
max_effective_size: 150 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 12 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 786432
	imagick::RESOURCETYPE_MAP: 12 GB
	imagick::RESOURCETYPE_MEMORY: 6 GB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, APNG, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CR3, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, J2C, J2K, JBG, JBIG, JNG, JNX, JP2, JPC, JPE, JPEG, JPG, JPM, JPS, JPT, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, POCKETMOD, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIDEO, VIFF, VIPS, VST, WBMP, WEBM, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: 2.2.5
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 5.10.76-linuxkit x86_64
httpd_software: nginx/1.21.1
php_version: 7.3.29 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: 60
upload_max_filesize: 150m
php_post_max_size: 150m
curl_version: 7.61.1 OpenSSL/1.1.1g
suhosin: false
imagick_availability: true
pretty_permalinks: true

### wp-database ###

extension: mysqli
server_version: 10.3.32-MariaDB-1:10.3.32+maria~focal
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $
max_allowed_packet: 16777216
max_connections: 100

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/html/wp-content
WP_PLUGIN_DIR: /var/www/html/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### classifai ###

0: 1.7.0
1: no
2: undefined
3: 
	Configured: no
	API URL: 
	API username: 
	Post types: 
	Features: {"category":null, "keyword":null, "entity":null, "concept":null}
	Latest response: N/A
4: 
	Authenticated: no
	API URL: 
	Caption threshold: 75
	Latest response - Image Scan: N/A
	Latest response - Smart Cropping: N/A
	Latest response - OCR: N/A

`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by iansvo**
### Description of the Change

This change resolves a reported error that occurs due to the metaData key being missing from the initialTracks provided to Webamp.

 You can reproduce this error on the official CodeSandbox demo by just removing the metaData key: https://codesandbox.io/s/y0xypox60z.

Closes #46 

### How to test the Change
1. Load the block on any page and confirm no LockedStream promise errors appear in the console and the tracks have the correct metadata.

### Credits
Props @iansvo @ajmaurya99 

### Checklist:

- [X] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [X] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by iansvo** [comment]
One caveat to note here is that this behavior is only applied to the frontend of the site. It might be worth applying this same consideration to the editor interface, but it feels like a lower value-to-time ratio for that lift.

If we were to do it in the editor we'd just need to be able to get the attachment metadata via a JS method and then just do the same thing I'm doing in the frontend.js file when WebAmp is initialized.

**Review by Sidsector9 — DISMISSED** [review]
LGTM, tested well 👍

**Comment by jeffpaul** [comment]
@cadic resolving the merge conflict here and then merging this would be helpful, thanks!

**Comment by cadic** [comment]
@Sidsector9 this needs another review after conflicts resolved (just package-lock.json)

**Review by Sidsector9 — DISMISSED** [review]
Tested well 👍

**Review by Sidsector9 — APPROVED** [review]
Added a fix for JS linting errors

**Pull request merged**
