### PR TITLE
feat/45: add milkdrop visualizations

### LINKED ISSUE #45: add support for Milkdrop visualizations
### Is your enhancement related to a problem? Please describe.

As noted by Justin Tadlock here: https://wptavern.com/a-throwback-to-the-past-retro-winamp-block?utm_source=rss&utm_medium=rss&utm_campaign=a-throwback-to-the-past-retro-winamp-block
> If I had one wish for this plugin, it would be to see the addition of Milkdrop, the popular Winamp visualizer add-on.

We'll need to assess if this is available in Webamp and how that might render on mobile layouts, plus how you might change the various visualizations available (and whether that might be another block setting or not).

### Designs

image

### Describe alternatives you've considered

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Sidsector9**
### Description of the Change

This PR adds support for Milkdrop visualisations.

Closes #45 

### Screenshot

**Desktop:**

https://user-images.githubusercontent.com/17757960/198896952-41f86a90-eb2f-4160-9af8-b27044a9eec8.mp4

**Mobile:**

Screenshot 2022-10-31 at 12 31 19 AM

### Changelog Entry

> Added - Support for Milkdrop visualisations.

### Credits

Props @jeffpaul @gsarig @Sidsector9 

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Review by iamdharmesh — COMMENTED** [review]
Thanks for the PR @Sidsector9, Code looks good to me and it works fine as well, could you please help to fix the reported eslint errors before we proceed on merging this?

**Review by iamdharmesh — DISMISSED** [review]
Thanks for the changes @Sidsector9, as we discussed internally on slack I added milkdrop support to the admin player previewer. please help to take a look once whenever you get a chance. 

Thanks

**Comment by iansvo** [comment]
@iamdharmesh @jeffpaul Looks like the WPCS linter is failing here because it isn't able to detect the value for prefixes. I have tried updating the file `.phpcs.xml.dist` file but it appears the GitHub Action workflow isn't using that file or otherwise can't see the values. 

I don't have the repo permissions to modify the workflow, but if someone who does have access can test this we should be able to get it sorted.  Ultimately we need to set the value of `prefixes` to an empty string (otherwise this will flag previously non-existent errors). 

Is this something one of you can test for me? I can continue my evaluation of other behavior but I believe we'll need that resolved in order to move this forward anyway, right?

**Comment by iansvo** [comment]
I added some CSS to fix an editor-style bug when using the block preview. 

But otherwise, everything seems to function well and work as expected.

**Comment by jeffpaul** [comment]
Wondering if we could add some additional flags to that WPCS action to handle that?  https://github.com/10up/wpcs-action#usage

**Comment by iamdharmesh** [comment]
Thanks for phpcs config changes and checking on this @iansvo, it seems we had an issue in **10up/wpcs-action** and PR https://github.com/10up/wpcs-action/pull/20 has resolved it. So, we can ignore this for now as the workflow will be fixed once the new version is released for action.

Thanks.
cc: @jeffpaul

**Review by iamdharmesh — APPROVED** [review]

**Pull request merged**
